# Generated by Django 3.2.9 on 2021-11-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('challan_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=255, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Bi', 'Bike'), ('Ca', 'Car'), ('Tr', 'Truck'), ('Bu', 'Bus')], default='Bike', max_length=255)),
                ('challan_amount', models.CharField(max_length=255)),
                ('challan_time', models.DateTimeField(auto_now=True)),
                ('challan_location', models.TextField()),
                ('challan_status', models.CharField(choices=[('P', 'Paid'), ('NP', 'Not Paid')], max_length=255)),
            ],
        ),
    ]
