# Generated by Django 4.0.4 on 2022-07-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='violation_type',
            field=models.TextField(default='tt'),
            preserve_default=False,
        ),
    ]
