# Generated by Django 4.0.1 on 2022-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('NotPaid', 'Not Paid')], max_length=255),
        ),
        migrations.AlterField(
            model_name='challan',
            name='vehicle_type',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('Truck', 'Truck'), ('Bus', 'Bus')], default='Bike', max_length=255),
        ),
    ]
