# Generated by Django 4.0.1 on 2022-01-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challans', '0002_alter_challan_challan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('NotPaid', 'Not Paid')], default='NotPaid', max_length=255),
        ),
    ]
