# Generated by Django 4.0.1 on 2022-02-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alert_Image', models.ImageField(blank=True, upload_to='Alerts/%Y/%M')),
                ('Alert_Message', models.CharField(max_length=255)),
            ],
        ),
    ]
