# Generated by Django 4.0.1 on 2022-02-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminAlert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminalerts',
            name='Alert_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Alerts/%Y/%M'),
        ),
        migrations.AlterField(
            model_name='adminalerts',
            name='Alert_Message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
