# Generated by Django 4.0.1 on 2022-02-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminAlert', '0002_alter_adminalerts_alert_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alert_Image', models.ImageField(null=True, upload_to='Alerts/%Y/%M')),
            ],
        ),
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alert_Message', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminAlerts',
        ),
    ]
